### ISSUE TITLE
Add advanced char rules

### ISSUE THREAD

**Issue by innovimax** [Innovimax-SARL/mix-them#29]
- [x]  join https://en.wikipedia.org/wiki/Join_(Unix)
- [x] random-alt-char
- [x] more than 2 files
- [x]  zip-line https://en.wikipedia.org/wiki/Convolution_(computer_science)
- [x] zip-cell
- [x] zip-char

**Comment by innovimax-jim** [comment]
new rule taken into account.
need a deeper description in specifications.

**Comment by innovimax** [comment]
@innovimax-jim description of join https://shapeshed.com/unix-join/

**Comment by innovimax-jim** [comment]
@innovimax previous link seems to be unreadable

**Comment by innovimax** [comment]
#69
