### ISSUE TITLE
implement basic text rules

### ISSUE THREAD

**Issue by innovimax** [Innovimax-SARL/mix-them#5]
- [x] 1: will output file1
  - [x] 2: will output file2
  - [x] +: will output file1+file2 
  - [x] alt-line: will output one line of each starting with first line of file1
  - [x] alt-char: will output one char of each starting from first char of file1
  - [x] rand-alt-line [seed]: will output one line of each code randomly based on a seed for reproducibility

**Comment by innovimax-jim** [comment]
@innovimax rule "+" has to be added ? (not appears in documentation)

**Comment by innovimax** [comment]
yes we add "+"

**Comment by innovimax-jim** [comment]
need to update arguments management for "seed" parameter

**Comment by innovimax-jim** [comment]
ramdom-alt-line implemented with a default seed for the moment

**Comment by innovimax-jim** [comment]
@innovimax  all  basic text rules implemented
