### ISSUE TITLE
use java.util.logging.Logger

### ISSUE THREAD

**Issue by innovimax** [Innovimax-SARL/mix-them#72]

**Comment by innovimax-jim** [comment]
@innovimax  we have to find a way to disable logging in pitest
This causes a Travis job aborting due to : "log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over). The job has been terminated"

**Comment by innovimax-jim** [comment]
tried to set a system environment variable to disable logging when executing pitest but this doesn't work

**Comment by innovimax-jim** [comment]
tried <avoidCallsTo>java.util.logging</avoidCallsTo> but doesn't change anything

**Comment by innovimax-jim** [comment]
tried pitest verbose=false but doesn't avoid mixthem logging

**Comment by innovimax-jim** [comment]
tried pitest jmvArgs with -Dmixthem.logging=false and it's working
no more logging when executing test suite

**Comment by innovimax-jim** [comment]
@innovimax logging in console done.
